# Generated by Django 4.2.5 on 2023-09-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao_da_cozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_estrelas', models.IntegerField()),
                ('id_do_usuario', models.IntegerField()),
                ('data_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao_de_alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_do_prato', models.IntegerField()),
                ('numero_de_estrelas', models.IntegerField()),
                ('id_do_usuario', models.IntegerField()),
                ('data_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('Numero_do_bilhete', models.CharField(max_length=50)),
                ('funcao', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('permissao', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('data_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infomacao_de_tempetatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_ambiental', models.FloatField()),
                ('temperatura_do_contentor', models.FloatField()),
                ('data_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prato_do_dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_prato', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
                ('chefe', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='')),
                ('caloria', models.FloatField()),
                ('data_refeicao', models.DateTimeField()),
                ('data_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_entrada', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('observacao', models.CharField(max_length=50)),
                ('data_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
