# Generated by Django 4.2.5 on 2023-09-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ocupacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ocupacao')),
            ],
        ),
    ]
