# Generated by Django 4.2.5 on 2023-09-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meumodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeuModelo',
        ),
    ]
