# Generated by Django 4.2.5 on 2023-10-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_meumodelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao_da_cozinha',
            name='descricao',
            field=models.CharField(default='silviosimon', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao_da_cozinha',
            name='foto',
            field=models.CharField(default='silviosimon', max_length=150),
            preserve_default=False,
        ),
    ]
