# Generated by Django 4.2.5 on 2023-10-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_avaliacao_da_cozinha_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao_da_cozinha',
            name='descricao',
            field=models.CharField(default='cozinha fundada em 2023', max_length=150),
        ),
        migrations.AlterField(
            model_name='avaliacao_da_cozinha',
            name='foto',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYH6pyBlIVud-kWaaevSC4R6WlycRrY8BUAA&usqp=CAU', max_length=150),
        ),
    ]
