# Generated by Django 4.2.5 on 2023-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_avaliacao_da_cozinha_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupacao',
            name='co2',
            field=models.CharField(default='23%', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocupacao',
            name='humidade',
            field=models.CharField(default='23%', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocupacao',
            name='temperatura',
            field=models.FloatField(default=15.0),
            preserve_default=False,
        ),
    ]
