# Generated by Django 4.2.5 on 2023-10-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ocupacao_co2_ocupacao_humidade_ocupacao_temperatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao_da_cozinha',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='avaliacao_da_cozinha',
            name='foto',
        ),
    ]
