# Generated by Django 4.2.5 on 2023-10-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cozinha_avaliacao_da_cozinha_id_da_cozinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao_da_cozinha',
            name='id_da_cozinha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cozinha'),
        ),
    ]
