# Generated by Django 4.2.5 on 2023-10-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_avaliacao_da_cozinha_id_da_cozinha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao_da_cozinha',
            name='id_da_cozinha',
        ),
    ]
