# Generated by Django 4.2.5 on 2023-10-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_avaliacao_da_cozinha_id_da_cozinha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cozinha',
        ),
    ]
